### ISSUE TITLE
[BUG] Error when fetching pack comments when on 11th page or later

### ISSUE THREAD

**Issue by jonahlikescookies** [MesterMan03/Bedlessbot#20]
**Describe the bug**
After the 10th page of pack comments, the API seems to break and fails to fetch comments. This limits the amount of comments to 100, which is probably not enough in the long run.

**To Reproduce**
1. Clone the repo(follow steps in README)
2. In `src/dashboard/api-test.ts`, change the 50 in line 27 to 101
3. Run `bun devdash`
4. Open the comments for any pack
5. Move to the next page until you hit the 11th page

**Expected behavior**
It is expected that for any comment page, the page should load properly.

**Actual behavior**
After the 10th page, any comment pages fail to load.

**Screenshots**
![image](https://github.com/user-attachments/assets/d0e3943c-7922-42ec-8b23-28483d07ec0b)

**Dashboard only - Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126

**Comment by jonahlikescookies** [comment]
The cause of the issue seems to be from line 169 in `api-test.ts`. Maybe this was left untouched when `api/comments/maxpage` was added?

**Comment by MesterMan03** [comment]
Good catch, I believe this used to be a hard limit for testing in the early development days before a proper max page detection was implemented, and I only updated the prod API with it, not the dev.
